### ISSUE TITLE
[feat] add notification channel for flag updates

### ISSUE THREAD

**Issue by zhouzhuojie** [openflagr/flagr-archived#30]
Teams need more visibility into how and when flags are updated. For example, Email or Slack notifications can be good channels.

Not sure if this feature is a good addon to the current Flagr setup. Maybe we can build it in Flagr, maybe we can expose Flagr webhooks and let other applications implement it.

**Comment by gedw99** [comment]
Also it would be good if I can get a web hook or similar to then control apdating users , apps or anything else I want.

the web hook just needs to have a decent amount of content so I can determine which users are effected so that I can then alert them.

I don’t know how flagr does this under the hood with PostgreSQL, but I imagine the outbox pattern would be a good way if it does not already use this
